### ISSUE TITLE
ERROR:ZeroDivisionError: division by zero 

### ISSUE THREAD

**Issue by RumengYi** [nyoki-mtl/pytorch-segmentation#18]
how can i slove this problem when i run python train.py ../config/pascal_unet_res18_scse.yaml?
Traceback (most recent call last):
  File "train.py", line 159, in <module>
    loss = loss_fn(preds, labels)
  File "/home/yirumeng/anaconda3/envs/Pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yirumeng/code/CAM/pytorch-segmentation-master/src/losses/multi/__init__.py", line 26, in forward
    loss = self.criterion(preds, labels)
  File "/home/yirumeng/anaconda3/envs/Pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yirumeng/code/CAM/pytorch-segmentation-master/src/losses/multi/lovasz_loss.py", line 77, in forward
    total_loss += lovasz_softmax_flat(prb, lbl, self.ignore_index, self.only_present)
  File "/home/yirumeng/code/CAM/pytorch-segmentation-master/src/losses/multi/lovasz_loss.py", line 56, in lovasz_softmax_flat
    return total_loss / cnt
ZeroDivisionError: division by zero

**Comment by carlodizon03** [comment]
try:
        z = total_loss / cnt
    except ZeroDivisionError:
        z = 0
    return z
